version: '3.9' # Docker Compose file version

services:
  db:
    image: postgres:15 # Use the latest stable PostgreSQL image
    restart: always # Restart container if it crashes
    environment:
      POSTGRES_DB: ${DB_NAME} # Database name
      POSTGRES_USER: ${DB_USER} # Default user
      POSTGRES_PASSWORD: ${DB_PASS} # Default password
    ports:
      - '5432:5432' # Map local port 5432 to container's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent volume for DB data
      - ./db-backups:/backups # Folder to store database backups

  backend:
    build: ./backend/app   # Build from current directory (Dockerfile)
    ports:
      - '3000:3000' # Expose backend port     
    env_file: # Environment variables for backend connection to DB
      - .env.local
    depends_on:
      - db # Wait for the db service before starting
    volumes:
      - .:/usr/src/app # Mount local folder into container (useful in dev)
    command: npm start # Start backend using npm

volumes:
  postgres_data: # Declare named volume for PostgreSQL data
