name: Bug Report
description: Bug Report template for BodyHealing
title: "[Bug - short name]"
labels: [yoganka, bug]
projects: ["MMadejsza/Yoganka.pl_Workflow"]
assignees: MMadejsza
body:
  - type: textarea
    id: desc
    attributes:
      label: 📝 Bug Description
      description: Clearly define WHAT the problem is and WHEN it occurs.
      placeholder: "As specific as possible."
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 📱 Mobile/Tablet/Desktop?
      multiple: true
      options:
        - 📱 Mobile
        - 📱 Mobile (horizontal)
        - 📔 Tablet
        - 📔 Tablet (horizontal)
        - 💻 Desktop
      default: 0
  - type: dropdown
    id: browsers
    attributes:
      label: 🎯 What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
      default: 0
  - type: dropdown
    id: priority
    attributes:
      label: 📆 How urgent is it?
      description: For example, is it important strategically (like for upcoming events) or is it just "Would be nice to have"?
      options:
        - 💥 ASAP
        - ☝️ 1-2 weeks
        - 🕐 No specific time
    validations:
      required: true
  - type: dropdown
    id: files
    attributes:
      label: 📷 Have you uploaded all necessary media/files to Google Drive?
      description: Upload all necessary files to Google Drive in a PROPERLY named directory (following our previous workflow). For example: event photos, the correct partner's logo files, properly named templates with dates, etc.
      options:
        - 💪 Yes
        - 👎 No
        - ❔ Not needed/Not sure if needed
        - ☝️ Partially - not organized
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 📂 Additional Notes that may help
      description: Who noticed it? Add any additional notes that may help track the problem, including screenshots, links, or examples to clarify the task requirements. 
      placeholder: "Optional"
