name: Bug Report
description: Bug Report template for BodyHealing
title: "[Bug]"
labels: ["yoganka", "bug"]
projects: ["MMadejsza/Yoganka.pl_Workflow"]
assignees:
  - MMadejsza
body:
  - type: textarea
    id: desc
    attributes:
      label: 📝 Bug Description
      description: Clearly define WHAT is the problem and WHEN it occurs.
      placeholder: "As specific as you can."
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 📱 Mobile/Tablet/Desktop?
      multiple: true
      options:
        - 📱 Mobile
        - 📱 Mobile horizontally
        - 📔 Tablet
        - 📔 Tablet horizontally
        - 💻 Desktop
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
      validations:
        required: true
  - type: textarea
    id: notes
    attributes:
      label: 📂 Additional Notes that may help
      description: Who noticed it? Add any additional notes that may help to track the problem down, screenshots links, or examples to clarify the task requirements. 
      placeholder: "Optional" 
