name: Task / Bussiness Requirement Form
description: Feature/Change Proposition template for BodyHealing
title: "[Task]"
labels: ["yoganka", "Feature"]
projects: ["MMadejsza/7"]
assignees:
  - MMadejsza
body:
  - type: textarea
    id: desc
    attributes:
      label: 📝 Task Description
      description: Clearly define what you think about.
      placeholder: "Here!"
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: 📌 Expectations Bullet Points
      description: List starting from "-" what it is supposed to be (shortlist).
      placeholder: "Here!"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 📂 Additional Notes
      description: Add any additional notes, screenshots links, or examples to clarify the task requirements.
      placeholder: "Here!" 
  - type: dropdown
    id: priority
    attributes:
      label: How urgent it is?
      description: Fo example is it important strategically like for upcoming events or Is it "Would be nice to have"?
      options:
        - ASAP
        - 1-2 weeks
        - Non-specified in time
      default: 2
    validations:
      required: true
