name: Task / Bussiness Requirement Form
description: Feature/Change Proposition template for BodyHealing
title: ""
labels: ["yoganka", "Feature"]
projects: ["MMadejsza/7"]
assignees:
  - MMadejsza
body:
  - type: textarea
    id: desc
    attributes:
      label: 📝 Task Description
      description: Clearly define what you think about.
      placeholder: "Here!"
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: 📌 Expectations Bullet Points
      description: List starting from "-" what it is supposed to be (shortlist).
      placeholder: "Here!"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 📂 Additional Notes
      description: Add any additional notes, screenshots links, or examples to clarify the task requirements.
      placeholder: "Here!" 
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
