//! HELPER FUNCTIONS
export const containsProfanity = value => {
  const lowerValue = value.toLowerCase();
  return profanityList.some(word => lowerValue.includes(word));
};
export const isNotEmpty = value => {
  return value.trim() !== '';
};
export const hasMinLength = (value, minLength) => {
  return value.length >= minLength;
};
export const equalsToOtherValue = (value, otherValue) => {
  return value === otherValue;
};
export const profanityList = [
  'chuj',
  'chuja',
  'chujek',
  'chuju',
  'chujem',
  'chujnia',
  'chujowy',
  'chujowa',
  'chujowe',
  'cipa',
  'cipę',
  'cipe',
  'cipą',
  'cipie',
  'dojebać',
  'dojebac',
  'dojebie',
  'dojebał',
  'dojebal',
  'dojebała',
  'dojebala',
  'dojebałem',
  'dojebalem',
  'dojebałam',
  'dojebalam',
  'dojebię',
  'dojebie',
  'dopieprzać',
  'dopieprzac',
  'dopierdalać',
  'dopierdalac',
  'dopierdala',
  'dopierdalał',
  'dopierdalal',
  'dopierdalała',
  'dopierdalala',
  'dopierdoli',
  'dopierdolił',
  'dopierdolil',
  'dopierdolę',
  'dopierdole',
  'dopierdoli',
  'dopierdalający',
  'dopierdalajacy',
  'dopierdolić',
  'dopierdolic',
  'dupa',
  'dupie',
  'dupą',
  'dupcia',
  'dupeczka',
  'dupy',
  'dupe',
  'huj',
  'hujek',
  'hujnia',
  'huja',
  'huje',
  'hujem',
  'huju',
  'jebać',
  'jebac',
  'jebał',
  'jebal',
  'jebie',
  'jebią',
  'jebia',
  'jebak',
  'jebaka',
  'jebal',
  'jebał',
  'jebany',
  'jebane',
  'jebanka',
  'jebanko',
  'jebankiem',
  'jebanymi',
  'jebana',
  'jebanym',
  'jebanej',
  'jebaną',
  'jebana',
  'jebani',
  'jebanych',
  'jebanymi',
  'jebcie',
  'jebiący',
  'jebiacy',
  'jebiąca',
  'jebiaca',
  'jebiącego',
  'jebiacego',
  'jebiącej',
  'jebiacej',
  'jebia',
  'jebią',
  'jebie',
  'jebię',
  'jebliwy',
  'jebnąć',
  'jebnac',
  'jebnąc',
  'jebnać',
  'jebnął',
  'jebnal',
  'jebną',
  'jebna',
  'jebnęła',
  'jebnela',
  'jebnie',
  'jebnij',
  'jebut',
  'koorwa',
  'kórwa',
  'kurestwo',
  'kurew',
  'kurewski',
  'kurewska',
  'kurewskiej',
  'kurewską',
  'kurewska',
  'kurewsko',
  'kurewstwo',
  'kurwa',
  'kurwaa',
  'kurwami',
  'kurwą',
  'kurwe',
  'kurwę',
  'kurwie',
  'kurwiska',
  'kurwo',
  'kurwy',
  'kurwach',
  'kurwami',
  'kurewski',
  'kurwiarz',
  'kurwiący',
  'kurwica',
  'kurwić',
  'kurwic',
  'kurwidołek',
  'kurwik',
  'kurwiki',
  'kurwiszcze',
  'kurwiszon',
  'kurwiszona',
  'kurwiszonem',
  'kurwiszony',
  'kutas',
  'kutasa',
  'kutasie',
  'kutasem',
  'kutasy',
  'kutasów',
  'kutasow',
  'kutasach',
  'kutasami',
  'matkojebca',
  'matkojebcy',
  'matkojebcą',
  'matkojebca',
  'matkojebcami',
  'matkojebcach',
  'nabarłożyć',
  'najebać',
  'najebac',
  'najebał',
  'najebal',
  'najebała',
  'najebala',
  'najebane',
  'najebany',
  'najebaną',
  'najebana',
  'najebie',
  'najebią',
  'najebia',
  'naopierdalać',
  'naopierdalac',
  'naopierdalał',
  'naopierdalal',
  'naopierdalała',
  'naopierdalala',
  'naopierdalała',
  'napierdalać',
  'napierdalac',
  'napierdalający',
  'napierdalajacy',
  'napierdolić',
  'napierdolic',
  'nawpierdalać',
  'nawpierdalac',
  'nawpierdalał',
  'nawpierdalal',
  'nawpierdalała',
  'nawpierdalala',
  'obsrywać',
  'obsrywac',
  'obsrywający',
  'obsrywajacy',
  'odpieprzać',
  'odpieprzac',
  'odpieprzy',
  'odpieprzył',
  'odpieprzyl',
  'odpieprzyła',
  'odpieprzyla',
  'odpierdalać',
  'odpierdalac',
  'odpierdol',
  'odpierdolił',
  'odpierdolil',
  'odpierdoliła',
  'odpierdolila',
  'odpierdoli',
  'odpierdalający',
  'odpierdalajacy',
  'odpierdalająca',
  'odpierdalajaca',
  'odpierdolić',
  'odpierdolic',
  'odpierdoli',
  'odpierdolił',
  'opieprzający',
  'opierdalać',
  'opierdalac',
  'opierdala',
  'opierdalający',
  'opierdalajacy',
  'opierdol',
  'opierdolić',
  'opierdolic',
  'opierdoli',
  'opierdolą',
  'opierdola',
  'piczka',
  'pieprznięty',
  'pieprzniety',
  'pieprzony',
  'pierdel',
  'pierdlu',
  'pierdolą',
  'pierdola',
  'pierdolący',
  'pierdolacy',
  'pierdoląca',
  'pierdolaca',
  'pierdol',
  'pierdole',
  'pierdolenie',
  'pierdoleniem',
  'pierdoleniu',
  'pierdolę',
  'pierdolec',
  'pierdola',
  'pierdolą',
  'pierdolić',
  'pierdolicie',
  'pierdolic',
  'pierdolił',
  'pierdolil',
  'pierdoliła',
  'pierdolila',
  'pierdoli',
  'pierdolnięty',
  'pierdolniety',
  'pierdolisz',
  'pierdolnąć',
  'pierdolnac',
  'pierdolnął',
  'pierdolnal',
  'pierdolnęła',
  'pierdolnela',
  'pierdolnie',
  'pierdolnięty',
  'pierdolnij',
  'pierdolnik',
  'pierdolona',
  'pierdolone',
  'pierdolony',
  'pierdołki',
  'pierdzący',
  'pierdzieć',
  'pierdziec',
  'pizda',
  'pizdą',
  'pizde',
  'pizdę',
  'piździe',
  'pizdzie',
  'pizdnąć',
  'pizdnac',
  'pizdu',
  'podpierdalać',
  'podpierdalac',
  'podpierdala',
  'podpierdalający',
  'podpierdalajacy',
  'podpierdolić',
  'podpierdolic',
  'podpierdoli',
  'pojeb',
  'pojeba',
  'pojebami',
  'pojebani',
  'pojebanego',
  'pojebanemu',
  'pojebani',
  'pojebany',
  'pojebanych',
  'pojebanym',
  'pojebanymi',
  'pojebem',
  'pojebać',
  'pojebac',
  'pojebalo',
  'popierdala',
  'popierdalac',
  'popierdalać',
  'popierdolić',
  'popierdolic',
  'popierdoli',
  'popierdolonego',
  'popierdolonemu',
  'popierdolonym',
  'popierdolone',
  'popierdoleni',
  'popierdolony',
  'porozpierdalać',
  'porozpierdala',
  'porozpierdalac',
  'poruchac',
  'poruchać',
  'przejebać',
  'przejebane',
  'przejebac',
  'przyjebali',
  'przepierdalać',
  'przepierdalac',
  'przepierdala',
  'przepierdalający',
  'przepierdalajacy',
  'przepierdalająca',
  'przepierdalajaca',
  'przepierdolić',
  'przepierdolic',
  'przyjebać',
  'przyjebac',
  'przyjebie',
  'przyjebała',
  'przyjebala',
  'przyjebał',
  'przyjebal',
  'przypieprzać',
  'przypieprzac',
  'przypieprzający',
  'przypieprzajacy',
  'przypieprzająca',
  'przypieprzajaca',
  'przypierdalać',
  'przypierdalac',
  'przypierdala',
  'przypierdoli',
  'przypierdalający',
  'przypierdalajacy',
  'przypierdolić',
  'przypierdolic',
  'qrwa',
  'rozjebać',
  'rozjebac',
  'rozjebie',
  'rozjebała',
  'rozjebią',
  'rozpierdalać',
  'rozpierdalac',
  'rozpierdala',
  'rozpierdolić',
  'rozpierdolic',
  'rozpierdole',
  'rozpierdoli',
  'rozpierducha',
  'skurwić',
  'skurwiel',
  'skurwiela',
  'skurwielem',
  'skurwielu',
  'skurwysyn',
  'skurwysynów',
  'skurwysynow',
  'skurwysyna',
  'skurwysynem',
  'skurwysynu',
  'skurwysyny',
  'skurwysyński',
  'skurwysynski',
  'skurwysyństwo',
  'skurwysynstwo',
  'spieprzać',
  'spieprzac',
  'spieprza',
  'spieprzaj',
  'spieprzajcie',
  'spieprzają',
  'spieprzaja',
  'spieprzający',
  'spieprzajacy',
  'spieprzająca',
  'spieprzajaca',
  'spierdalać',
  'spierdalac',
  'spierdala',
  'spierdalał',
  'spierdalała',
  'spierdalal',
  'spierdalalcie',
  'spierdalala',
  'spierdalający',
  'spierdalajacy',
  'spierdolić',
  'spierdolic',
  'spierdoli',
  'spierdoliła',
  'spierdoliło',
  'spierdolą',
  'spierdola',
  'srać',
  'srac',
  'srający',
  'srajacy',
  'srając',
  'srajac',
  'sraj',
  'sukinsyn',
  'sukinsyny',
  'sukinsynom',
  'sukinsynowi',
  'sukinsynów',
  'sukinsynow',
  'śmierdziel',
  'udupić',
  'ujebać',
  'ujebac',
  'ujebał',
  'ujebal',
  'ujebana',
  'ujebany',
  'ujebie',
  'ujebała',
  'ujebala',
  'upierdalać',
  'upierdalac',
  'upierdala',
  'upierdoli',
  'upierdolić',
  'upierdolic',
  'upierdoli',
  'upierdolą',
  'upierdola',
  'upierdoleni',
  'wjebać',
  'wjebac',
  'wjebie',
  'wjebią',
  'wjebia',
  'wjebiemy',
  'wjebiecie',
  'wkurwiać',
  'wkurwiac',
  'wkurwi',
  'wkurwia',
  'wkurwiał',
  'wkurwial',
  'wkurwiający',
  'wkurwiajacy',
  'wkurwiająca',
  'wkurwiajaca',
  'wkurwić',
  'wkurwic',
  'wkurwi',
  'wkurwiacie',
  'wkurwiają',
  'wkurwiali',
  'wkurwią',
  'wkurwia',
  'wkurwimy',
  'wkurwicie',
  'wkurwiacie',
  'wkurwić',
  'wkurwic',
  'wkurwia',
  'wpierdalać',
  'wpierdalac',
  'wpierdalający',
  'wpierdalajacy',
  'wpierdol',
  'wpierdolić',
  'wpierdolic',
  'wpizdu',
  'wyjebać',
  'wyjebac',
  'wyjebali',
  'wyjebał',
  'wyjebac',
  'wyjebała',
  'wyjebały',
  'wyjebie',
  'wyjebią',
  'wyjebia',
  'wyjebiesz',
  'wyjebie',
  'wyjebiecie',
  'wyjebiemy',
  'wypieprzać',
  'wypieprzac',
  'wypieprza',
  'wypieprzał',
  'wypieprzal',
  'wypieprzała',
  'wypieprzala',
  'wypieprzy',
  'wypieprzyła',
  'wypieprzyla',
  'wypieprzył',
  'wypieprzyl',
  'wypierdal',
  'wypierdalać',
  'wypierdalac',
  'wypierdala',
  'wypierdalaj',
  'wypierdalał',
  'wypierdalal',
  'wypierdalała',
  'wypierdalala',
  'wypierdalać',
  'wypierdolić',
  'wypierdolic',
  'wypierdoli',
  'wypierdolimy',
  'wypierdolicie',
  'wypierdolą',
  'wypierdola',
  'wypierdolili',
  'wypierdolił',
  'wypierdolil',
  'wypierdoliła',
  'wypierdolila',
  'zajebać',
  'zajebac',
  'zajebie',
  'zajebią',
  'zajebia',
  'zajebiał',
  'zajebial',
  'zajebała',
  'zajebiala',
  'zajebali',
  'zajebana',
  'zajebani',
  'zajebane',
  'zajebany',
  'zajebanych',
  'zajebanym',
  'zajebanymi',
  'zajebiste',
  'zajebisty',
  'zajebistych',
  'zajebista',
  'zajebistym',
  'zajebistymi',
  'zajebiście',
  'zajebiscie',
  'zapieprzyć',
  'zapieprzyc',
  'zapieprzy',
  'zapieprzył',
  'zapieprzyl',
  'zapieprzyła',
  'zapieprzyla',
  'zapieprzą',
  'zapieprza',
  'zapieprzy',
  'zapieprzymy',
  'zapieprzycie',
  'zapieprzysz',
  'zapierdala',
  'zapierdalać',
  'zapierdalac',
  'zapierdalaja',
  'zapierdalał',
  'zapierdalaj',
  'zapierdalajcie',
  'zapierdalała',
  'zapierdalala',
  'zapierdalali',
  'zapierdalający',
  'zapierdalajacy',
  'zapierdolić',
  'zapierdolic',
  'zapierdoli',
  'zapierdolił',
  'zapierdolil',
  'zapierdoliła',
  'zapierdolila',
  'zapierdolą',
  'zapierdola',
  'zapierniczać',
  'zapierniczający',
  'zasrać',
  'zasranym',
  'zasrywać',
  'zasrywający',
  'zesrywać',
  'zesrywający',
  'zjebać',
  'zjebac',
  'zjebał',
  'zjebal',
  'zjebała',
  'zjebala',
  'zjebana',
  'zjebią',
  'zjebali',
  'zjeby',
  ,
  'хуй',
  'хую',
  'хуйові',
  'хуйовий',
  'хуйом',
  'хуйах',
  'хуй!',
  ,
  // 14. "пизда" (pizda)
  'пизда',
  'пизди',
  'пизді',
  'пизду',
  'пиздою',
  'пиздах',
  'пизда!',
  ,
  // 15. "блядь" (blyad)
  'блядь',
  'бляді',
  'блядій',
  'бляду',
  'блядью',
  'блядах',
  'блядь!',
  ,
  // 16. "сука" (suka)
  'сука',
  'суки',
  'суці',
  'суку',
  'сукою',
  'суках',
  'сука!',
  ,
  // 17. "ёбать" (yobaty)
  'ёбать',
  'ёбання',
  'ёбаного',
  'ёбаному',
  'ёбаним',
  'ёбаних',
  'ёбать!',
  ,
  // 18. "хуйло" (hujlo)
  'хуйло',
  'хуйла',
  'хуйлові',
  'хуйловий',
  'хуйлом',
  'хуйлах',
  'хуйло!', // Grupa 1 – słowo bazowe "хуй"
  'хуй',
  'хую',
  'хуйовий',
  'хуйова',
  'хуйове',
  'хуйової',
  'хуйові',
  'хуйом',
  'хуйах',
  'хуйовим',
  'хуйовою',
  'хуйовому',
  'хуйовій',
  'хуйовці',

  // Grupa 2 – słowo bazowe "пизда"
  'пизда',
  'пизди',
  'пизді',
  'пизду',
  'пиздою',
  'пиздах',
  'пиздовий',
  'пиздова',
  'пиздове',
  'пиздової',
  'пиздові',
  'пиздовим',
  'пиздовою',
  'пиздовому',

  // Grupa 3 – słowo bazowe "блядь"
  'блядь',
  'бляді',
  'блядій',
  'бляду',
  'блядью',
  'блядах',
  'блядський',
  'блядська',
  'блядське',
  'блядської',
  'блядські',
  'блядським',
  'блядською',
  'блядському',

  // Grupa 4 – słowo bazowe "сука"
  'сука',
  'суки',
  'сукою',
  'суках',
  'суковий',
  'сукова',
  'сукове',
  'сукової',
  'сукові',
  'суковим',
  'суків',
  'сукинь',
  'суко',
  'сучко',

  // Grupa 5 – słowo bazowe "єбати" (odpowiednik rosyjskiego "ёбать")
  'єбати',
  'єбаний',
  'єбаного',
  'єбаному',
  'єбаним',
  'єбаних',
  'єбаною',
  'єбашити',
  'єбнув',
  'єбнула',
  'єбнувши',
  'єбаність',
  'єбаністю',
  'єбаність',

  // Grupa 6 – słowo bazowe "хуйло"
  'хуйло',
  'хуйла',
  'хуйловий',
  'хуйлова',
  'хуйлове',
  'хуйлової',
  'хуйлові',
  'хуйлом',
  'хуйлових',
  'хуйловим',
  'хуйловою',
  'хуйловому',
  'хуйловій',
  'хуйловці',

  // Grupa 7 – słowo bazowe "мудак"
  'мудак',
  'мудака',
  'мудаковий',
  'мудакова',
  'мудакове',
  'мудакової',
  'мудакові',
  'мудаком',
  'мудакових',
  'мудаковим',
  'мудаковою',
  'мудаковому',
  'мудаковій',
  'мудачок',

  // Grupa 8 – słowo bazowe "сучка"
  'сучка',
  'сучки',
  'сучкою',
  'сучках',
  'сучковий',
  'сучкова',
  'сучкове',
  'сучкової',
  'сучкові',
  'сучковим',
  'сучок',
  'сучонь',
  'сучар',
  'сучаро',

  // Grupa 9 – słowo bazowe "пиздюк"
  'пиздюк',
  'пиздюка',
  'пиздюковий',
  'пиздюкова',
  'пиздюкове',
  'пиздюкової',
  'пиздюкові',
  'пиздюком',
  'пиздюках',
  'пиздюки',
  'пиздюкатий',
  'пиздюкана',
  'пиздючна',
  'пиздючий',

  // Grupa 10 – słowo bazowe "бляха"
  'бляха',
  'блях',
  'бляхнути',
  'бляхнув',
  'бляхла',
  'бляхло',
  'бляхую',
  'бляхнувши',
  'бляхатий',
  'бляхати',
  'бляхнутий',
  'бляхнута',
  'бляхнута',
  'бляхнута',

  // Grupa 11 – słowo bazowe "підхуй"
  'підхуй',
  'підхуя',
  'підхую',
  'підхуїв',
  'підхуячи',
  'підхуєм',
  'підхуйовий',
  'підхуйова',
  'підхуйове',
  'підхуйової',
  'підхуйові',
  'підхуйом',
  'підхуйах',
  'підхує',

  // Grupa 12 – słowo bazowe "нахуй"
  'нахуй',
  'нахуя',
  'нахую',
  'нахуйовий',
  'нахуйова',
  'нахуйове',
  'нахуйової',
  'нахуйові',
  'нахуйом',
  'нахуйах',
  'нахуйовим',
  'нахуйовою',
  'нахуйовому',
  'нахуйовій',

  // Grupa 13 – słowo bazowe "обхуя"
  'обхуя',
  'обхую',
  'обхуїв',
  'обхуячи',
  'обхуєм',
  'обхуйовий',
  'обхуйова',
  'обхуйове',
  'обхуйової',
  'обхуйові',
  'обхуйом',
  'обхуйах',
  'обхуй',
  'обхуй',

  // Grupa 14 – słowo bazowe "підпизд"
  'підпизд',
  'підпизда',
  'підпиздовий',
  'підпиздова',
  'підпиздове',
  'підпиздової',
  'підпиздові',
  'підпиздом',
  'підпиздів',
  'підпиздовим',
  'підпиздовою',
  'підпиздовому',
  'підпиздовій',
  'підпиздя',

  // Grupa 15 – słowo bazowe "нахуйовий"
  'нахуйовий',
  'нахуйова',
  'нахуйове',
  'нахуйової',
  'нахуйові',
  'нахуйом',
  'нахуйах',
  'нахуйовим',
  'нахуйовою',
  'нахуйовому',
  'нахуйовій',
  'нахуйовці',
  'нахуйовці',
  'нахуй',

  // Grupa 16 – słowo bazowe "опиздолити"
  'опиздолити',
  'опиздолитися',
  'опиздолений',
  'опиздолена',
  'опиздолене',
  'опиздоленою',
  'опиздолених',
  'опиздоленим',
  'опиздоленою',
  'опиздолених',
  'опиздолись',
  'опиздолив',
  'опиздолила',
  'опиздолило',

  // Grupa 17 – słowo bazowe "розхуїти"
  'розхуїти',
  'розхуїтися',
  'розхуй',
  'розхуя',
  'розхуїв',
  'розхуївши',
  'розхуїв',
  'розхуївся',
  'розхуїти',
  'розхуйовий',
  'розхуйова',
  'розхуйове',
  'розхуйової',
  'розхуйові',

  // Grupa 18 – słowo bazowe "захуй"
  'захуй',
  'захуя',
  'захуйовий',
  'захуйова',
  'захуйове',
  'захуйової',
  'захуйові',
  'захуйом',
  'захуйах',
  'захуйовим',
  'захуйовою',
  'захуйовому',
  'захуйовій',
  'захуйчик',

  // Grupa 19 – słowo bazowe "обсрати"
  'обсрати',
  'обсратися',
  'обсраний',
  'обсрана',
  'обсране',
  'обсраною',
  'обсраних',
  'обсраним',
  'обсраними',
  'обсраного',
  'обсраному',
  'обсраній',
  'обсрані',
  'обсратись',

  // Grupa 20 – słowo bazowe "засрати"
  'засрати',
  'засратися',
  'засраний',
  'засрана',
  'засране',
  'засраною',
  'засраних',
  'засраним',
  'засраними',
  'засраному',
  'засраній',
  'засрані',
  'засратись',
  'засрать',

  // Grupa 21 – słowo bazowe "обпиздолити"
  'обпиздолити',
  'обпиздолитися',
  'обпиздолений',
  'обпиздолена',
  'обпиздолене',
  'обпиздоленим',
  'обпиздолених',
  'обпиздоленою',
  'обпиздоленому',
  'обпиздолив',
  'обпиздолила',
  'обпиздолило',
  'обпиздолений',
  'обпиздолена',

  // Grupa 22 – słowo bazowe "нахуярити"
  'нахуярити',
  'нахуяритися',
  'нахуярений',
  'нахуярена',
  'нахуярене',
  'нахуяреною',
  'нахуярених',
  'нахуяреним',
  'нахуяреною',
  'нахуярених',
  'нахуярись',
  'нахуярив',
  'нахуярила',
  'нахуярило',

  // Grupa 23 – słowo bazowe "охуїти"
  'охуїти',
  'охуїтися',
  'охуїний',
  'охуїна',
  'охуїне',
  'охуїною',
  'охуїних',
  'охуїним',
  'охуїною',
  'охуїних',
  'охуїть',
  'охуїв',
  'охуїла',
  'охуїло',

  // Grupa 24 – słowo bazowe "охуяння"
  'охуяння',
  'охуяна',
  'охуяне',
  'охуяну',
  'охуянням',
  'охуяннях',
  'охуяному',
  'охуянній',
  'охуянці',
  'охуянний',
  'охуянним',
  'охуянною',
  'охуяному',
  'охуянці',

  // Grupa 25 – słowo bazowe "похуй"
  'похуй',
  'похуя',
  'похуйовий',
  'похуйова',
  'похуйове',
  'похуйової',
  'похуйові',
  'похуйом',
  'похуйах',
  'похуйовим',
  'похуйовою',
  'похуйовому',
  'похуйовій',
  'похуйчик',

  // Grupa 26 – słowo bazowe "похуячий"
  'похуячий',
  'похуячого',
  'похуячому',
  'похуячим',
  'похуячими',
  'похуячій',
  'похуячі',
  'похуячою',
  'похуячій',
  'похуячимось',
  'похуячий',
  'похуяч',
  'похуячка',
  'похуячці',

  // Grupa 27 – słowo bazowe "хуймат"
  'хуймат',
  'хуймата',
  'хуйматовий',
  'хуйматова',
  'хуйматове',
  'хуйматової',
  'хуйматові',
  'хуйматом',
  'хуйматах',
  'хуйматовим',
  'хуйматовою',
  'хуйматовому',
  'хуйматовій',
  'хуйматці',

  // Grupa 28 – słowo bazowe "нахуячий"
  'нахуячий',
  'нахуячого',
  'нахуячому',
  'нахуячим',
  'нахуячими',
  'нахуячій',
  'нахуячі',
  'нахуячою',
  'нахуячій',
  'нахуячимось',
  'нахуячий',
  'нахуяч',
  'нахуячка',
  'нахуячці',

  // Grupa 29 – słowo bazowe "опиздолити"
  'опиздолити',
  'опиздолитися',
  'опиздолений',
  'опиздолена',
  'опиздолене',
  'опиздоленою',
  'опиздолених',
  'опиздоленим',
  'опиздоленою',
  'опиздолених',
  'опиздолись',
  'опиздолив',
  'опиздолила',
  'опиздолило',

  // Grupa 30 – słowo bazowe "розпиздолити"
  'розпиздолити',
  'розпиздолитися',
  'розпиздолений',
  'розпиздолена',
  'розпиздолене',
  'розпиздоленим',
  'розпиздолених',
  'розпиздоленою',
  'розпиздоленому',
  'розпиздолись',
  'розпиздолив',
  'розпиздолила',
  'розпиздолило',
  'розпиздолений',

  // Grupa 31 – słowo bazowe "обсраний"
  'обсраний',
  'обсрана',
  'обсране',
  'обсраною',
  'обсраних',
  'обсраним',
  'обсраними',
  'обсраного',
  'обсраному',
  'обсраній',
  'обсрані',
  'обсраним',
  'обсраний',
  'обсран',

  // Grupa 32 – słowo bazowe "засраний"
  'засраний',
  'засрана',
  'засране',
  'засраною',
  'засраних',
  'засраним',
  'засраними',
  'засраному',
  'засраній',
  'засрані',
  'засраним',
  'засраний',
  'засран',
  'засранимось',

  // Grupa 33 – słowo bazowe "обпиздолити"
  'обпиздолити',
  'обпиздолитися',
  'обпиздолений',
  'обпиздолена',
  'обпиздолене',
  'обпиздоленим',
  'обпиздолених',
  'обпиздоленою',
  'обпиздоленому',
  'обпиздолив',
  'обпиздолила',
  'обпиздолило',
  'обпиздолений',
  'обпиздолена',

  // Grupa 34 – słowo bazowe "подпиздолити"
  'подпиздолити',
  'подпиздолитися',
  'подпиздолений',
  'подпиздолена',
  'подпиздолене',
  'подпиздоленим',
  'подпиздолених',
  'подпиздоленою',
  'подпиздоленому',
  'подпиздолив',
  'подпиздолила',
  'подпиздолило',
  'подпиздолений',
  'подпиздолена',

  // Grupa 35 – słowo bazowe "розхуїти"
  'розхуїти',
  'розхуїтися',
  'розхуй',
  'розхуя',
  'розхуїв',
  'розхуївши',
  'розхуїв',
  'розхуївся',
  'розхуїти',
  'розхуйовий',
  'розхуйова',
  'розхуйове',
  'розхуйової',
  'розхуйові',

  // Grupa 36 – słowo bazowe "виблядь"
  'виблядь',
  'вибляді',
  'виблядьовий',
  'виблядьова',
  'виблядьове',
  'виблядьової',
  'виблядьові',
  'виблядьом',
  'виблядях',
  'виблядовим',
  'виблядьовою',
  'виблядьовому',
  'виблядьовій',
  'виблядці',
];

//@ FIRST NAME RULESET
export const firstNameValidations = [
  {
    rule: value => value.trim() !== '',
    message: 'Imię nie może być puste',
  },
  {
    //  A-Z, polish and ukrainian symbols
    rule: value =>
      /^[A-Za-zÀ-ÿĄąĆćĘęŁłŃńÓóŚśŹźŻżА-Яа-яЁёІіЇїЄє\s'-]+$/.test(value),
    message: 'Imię może zawierać tylko litery, spacje, apostrofy i myślniki',
  },
  {
    rule: value => !containsProfanity(value),
    message: 'Generalna walidacja',
  },
  {
    rule: value => value.trim().length >= 2,
    message:
      '*podanie inicjałów może skutkować późniejszym usunięciem zgłoszenia',
  },
];
//@ LAST NAME RULESET
export const lastNameValidations = [
  {
    rule: value => value.trim() !== '',
    message: 'Nazwisko nie może być puste',
  },
  {
    rule: value =>
      /^[A-Za-zÀ-ÿĄąĆćĘęŁłŃńÓóŚśŹźŻżА-Яа-яЁёІіЇїЄє\s'-]+$/.test(value),
    message:
      'Nazwisko może zawierać tylko litery, spacje, apostrofy i myślniki',
  },
  {
    rule: value => !containsProfanity(value),
    message: 'Generalna walidacja',
  },
  {
    rule: value => value.trim().length >= 2,
    message:
      '*podanie inicjałów może skutkować późniejszym usunięciem zgłoszenia',
  },
];
//@ DOB RULESET
export const dobValidations = [
  {
    rule: value => value.trim() !== '',
    message: 'Data urodzenia nie może być pusta',
  },
  {
    // Checks if date is valid
    rule: value => {
      const date = new Date(value);
      return !isNaN(date.getTime());
    },
    message: 'Podaj prawidłową datę',
  },
  {
    // Can't be future
    rule: value => {
      const date = new Date(value);
      return date < new Date();
    },
    message: 'Data urodzenia nie może być w przyszłości',
  },
  {
    // Can't be future
    rule: value => {
      const birthDate = new Date(value);
      const today = new Date();
      let age = today.getFullYear() - birthDate.getFullYear();
      const m = today.getMonth() - birthDate.getMonth();

      // If birthday this year hasn't passed -> age --1
      if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
        age--;
      }

      return age >= 18;
    },
    message: 'Pełnoletność',
  },
];
//@ PHONE RULESET
export const phoneValidations = [
  {
    rule: value => /^[+\d\s()-]+$/.test(value),
    message: 'Tylko cyfry, spacje, -, (), +',
  },
  {
    // force to start from "+"
    // and check if 1-3 digits
    rule: value => {
      const trimmed = value.trim();
      const match = trimmed.match(/^\+(\d{1,3})/);
      return match !== null;
    },
    message: 'Numer kierunkowy (np. +48)',
  },
  {
    // must be 8-15 digits
    rule: value => {
      const digits = value.replace(/\D/g, '');
      return digits.length >= 8 && digits.length <= 15;
    },
    message: '8 do 15 cyfr',
  },
];
//@ EMAIL RULESET
export const emailValidations = [
  {
    // if empty
    rule: value => value.trim() !== '',
    message: 'Nie może być pusty',
  },
  {
    // if no @
    rule: value => value.includes('@'),
    message: 'Zawiera "@"',
  },
  {
    // if doesn't follow simple format name@domain.com
    rule: value => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value),
    message: 'W formacie jan@domena.com',
  },
];
//@ PASSWORD RULESET
export const passwordValidations = [
  {
    // if shorter than 8
    rule: value => hasMinLength(value, 8),
    message: 'Przynajmniej 8 znaków',
  },
  {
    // if at least 1x capital letter
    rule: value => /[A-Z]/.test(value),
    message: 'Przynajmniej jedna wielka litera',
  },
  {
    // if at least 1x special character (^ negation -> of a-z, A-Z and umbers what defines character)
    rule: value => /[^a-zA-Z0-9]/.test(value),
    message: 'Przynajmniej jeden znak specjalny',
  },
];
//@ CONFIRM PASSWORD RULESET
//  must be function to be able to pass other input value (1st password)
export const getConfirmedPasswordValidations = passwordValue => [
  {
    // if not equal
    rule: value => equalsToOtherValue(value, passwordValue),
    message: 'Musi być identyczne',
  },
];
//@ NOTES RULESET
export const notesValidations = [
  {
    // length
    rule: value => value.length <= 150,
    message: 'Max 150 znaków',
  },
  {
    rule: value => !containsProfanity(value),
    message: 'Generalna walidacja',
  },
];
//@ AMOUNT PAID RULESET
export const amountPaidValidations = [
  {
    rule: value => value.trim() !== '',
    message: 'Pole nie może być puste',
  },
  {
    rule: value => !isNaN(value) && Number(value) >= 0,
    message:
      'Kwota musi być liczbą (całkowitą lub zmiennoprzecinkową) i nie może być mniejsza niż 0.',
  },
];
//@ PAYMENT METHOD RULESET
export const paymentMethodValidations = [
  {
    rule: value => value.toString().trim() !== '',
    message: 'Pole nie może być puste',
  },
  {
    rule: value => [1, 2, 3].includes(Number(value)),
    message: 'Metoda płatności musi mieć wartość 1, 2 lub 3.',
  },
];
//@ LOCATION RULESET
export const locationValidations = [
  {
    rule: value => value.trim() !== '',
    message: 'Pole nie może być puste - widoczne dla klienta.',
  },
  {
    rule: value => value.length <= 25,
    message: 'Max 25 znaków - krótkie, rozpoznawcze bez szczegółów.',
  },
];
//@ PRODUCT NAME RULESET
export const productNameValidations = [
  {
    rule: value => value.trim() !== '',
    message: 'Pole nie może być puste',
  },
  {
    rule: value => value.length <= 25,
    message: 'Max 25 znaków',
  },
];
//@ PRODUCT DURATION RULESET
export const productDurationValidations = [
  {
    rule: value => value.toString().trim() !== '',
    message: 'Pole nie może być puste',
  },
  {
    rule: value => !isNaN(value) && Number(value) >= 0,
    message:
      'Czas w godzinach musi być liczbą (całkowitą lub zmiennoprzecinkową) i nie może być mniejsza niż 0.',
  },
  {
    rule: value => Number(value) % 0.25 == 0,
    message: 'Min skok co 15 minut czyli 0.25 godziny.',
  },
];
//@ PRICE RULESET
export const priceValidations = [
  {
    rule: value => value.toString().trim() !== '',
    message: 'Pole nie może być puste',
  },
  {
    rule: value => {
      const trimmed = value.toString().trim();
      if (/\s/.test(trimmed)) return false; // żadnych spacji!
      const num = Number(trimmed);
      return !isNaN(num);
    },
    message: 'Cena musi być poprawną liczbą i nie może zawierać spacji.',
  },
  {
    rule: value => {
      const num = Number(value);
      if (isNaN(num)) return false;
      const decimalPart = value.toString().split('.')[1];
      return !decimalPart || decimalPart.length <= 2;
    },
    message: 'Cena może mieć maksymalnie 2 miejsca po przecinku.',
  },
  {
    rule: value => Number(value) >= 0,
    message: 'Cena nie może być mniejsza niż 0.',
  },
];
